# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
        files: "(src/|tests/)"
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        files: "(src/|tests/)"
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        files: "(src/|tests/)"
